### ISSUE TITLE
Toast should have cursor pointer if `onClick`

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/nextcloud-dialogs#104]
- [ ] Have proper css cursor
- [ ] onClick should probably not be an empty function by default but undefined. That way we can properly detect and apply a class

**Comment by ChristophWurst** [comment]
> onClick should probably not be an empty function by default

It is. We just set one here https://github.com/nextcloud/nextcloud-dialogs/blob/687e368ee49c17787d108c5b6be9ab7f42e4512f/lib/toast.ts#L63. We could assign the completed options to a new variable and check for undefined at https://github.com/nextcloud/nextcloud-dialogs/blob/687e368ee49c17787d108c5b6be9ab7f42e4512f/lib/toast.ts#L85 with a custom class.

**Comment by skjnldsv** [comment]
Yep, I'm on it.


> > onClick should probably not be an empty function by default
> 
> It is. We just set one here
> 
> https://github.com/nextcloud/nextcloud-dialogs/blob/687e368ee49c17787d108c5b6be9ab7f42e4512f/lib/toast.ts#L63

Yes, that's my complain, having it as an empty function prevent us from detecting if the argument is provided :)
The original Toasitfy lib is using undefined

**Comment by ChristophWurst** [comment]
So we could just remove our default?

**Comment by skjnldsv** [comment]
Yes

**Comment by skjnldsv** [comment]
https://github.com/nextcloud/nextcloud-dialogs/pull/106/commits/d57f8646973c9a66702a82481217f94b46e440d7

**Comment by ChristophWurst** [comment]
Fine by me

**Comment by skjnldsv** [comment]
Fixed with undo pr #106
