### ISSUE TITLE
Docs are outdated

### ISSUE THREAD

**Issue by korelstar** [nextcloud/nextcloud-dialogs#206]
It looks like the documentation build on https://nextcloud.github.io/nextcloud-dialogs/ wasn't updated since #106

**Comment by skjnldsv** [comment]
cc @ChristophWurst

**Comment by ChristophWurst** [comment]
This is a regression of https://github.com/nextcloud/nextcloud-dialogs/commit/581db513238f94207557e47e6b9a39e14326343c#diff-6ac3f79fc25d95cd1e3d51da53a4b21b939437392578a35ae8cd6d5366ca5485

**Comment by skjnldsv** [comment]
Are they supposed to build automatically?

**Comment by ChristophWurst** [comment]
Yes, with every tag.

**Comment by ChristophWurst** [comment]
See the deleted Travis config.

**Comment by skjnldsv** [comment]
Oh sorry!
Most likely an easy fix with https://github.com/marketplace/actions/deploy-to-github-pages

**Comment by susnux** [comment]
Any news on this?

**Comment by ChristophWurst** [comment]
No, we still need someone who can revive the automatic build based on a Github action

**Comment by skjnldsv** [comment]
Done https://github.com/nextcloud/nextcloud-dialogs/blob/master/.github/workflows/static-pages.yml

**Comment by ChristophWurst** [comment]
Push to master?
