### ISSUE TITLE
Using svg files is BC break also

### ISSUE THREAD

**Issue by zorn-v** [nextcloud/nextcloud-dialogs#338]
You can not just upgrade 1.x to 3.x and run `npm run build` if you does not configure svg loader (like file-loader etc).
I think it SHOULD be in readme or changelog. 
Someone may just accept dependabot alert like this 
![изображение](https://user-images.githubusercontent.com/12619075/115134671-86d98a00-a055-11eb-9623-6c80d6be3c69.png)

**Comment by ChristophWurst** [comment]
That is documented at https://github.com/nextcloud/nextcloud-dialogs#toasts, right?

**Comment by zorn-v** [comment]
There is only "make sure that `@nextcloud/dialogs/styles/toast.scss` is included". In v1.x it also was included. But in v1 there was no SVG files, and webpack loader for it may be not configured in project
And you get something like
> ERROR in ../node_modules/@nextcloud/dialogs/styles/close-dark.svg 1:0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders

after upgrade this package

**Comment by ChristophWurst** [comment]
I see. Would you mind sending a PR to update the changelog with this and possibly the readme? This will be helpful for others.

I think for "my" apps this didn't show because there was already a svg loader in place.

Sorry for the inconveniences caused.
