### ISSUE TITLE
Erroneous security issue?

### ISSUE THREAD

**Issue by korelstar** [nextcloud/nextcloud-dialogs#339]
Is there an error in the security issue https://github.com/nextcloud/nextcloud-dialogs/security/advisories/GHSA-g3fq-3v3g-mh32 ?

It says that version 3.2.1 has patched the error (and `<3.2.1` is affected), but the latest published version is 3.1.2 !

**Comment by LukasReschke** [comment]
That should indeed be 3.1.2. Fixed now :)

https://github.com/nextcloud/nextcloud-dialogs/security/advisories/GHSA-g3fq-3v3g-mh32
