### ISSUE TITLE
Toastify dark mode regression

### ISSUE THREAD

**Issue by PVince81** [nextcloud/nextcloud-dialogs#629]
we can't rely on a class set on the body and more: https://github.com/nextcloud/nextcloud-dialogs/blob/febaa367090498fcde5fe2b36f06a827de184089/styles/toast.scss#L110

need to detect it directly from the browser

**Comment by nickvergessen** [comment]
> need to detect it directly from the browser

Not exactly, because your browser can be dark mode but you force bright mode in the settings.

But fixed in #630
