### ISSUE TITLE
Notification close button alignment issues

### ISSUE THREAD

**Issue by PVince81** [nextcloud/nextcloud-dialogs#631]
See https://github.com/nextcloud/server/pull/33307 for screenshots.
It worked fine with 3.1.2 and broken in 3.1.4.

3.1.3 brings in a PR that might be related: https://github.com/nextcloud/nextcloud-dialogs/pull/582

**Comment by nickvergessen** [comment]
Might be falsepositive as the local compiling seems to have been corrupted.

**Comment by nickvergessen** [comment]
https://github.com/nextcloud/server/pull/33307#issuecomment-1191600258

Seems like it

**Comment by PVince81** [comment]
it was first a local compilation issue on my side

now the next problem is that the files app seems to mess with the icon, but the settings page looks fine

I'm guessing that it's not a problem with the lib itself, so I'm closing it

follow up in https://github.com/nextcloud/server/pull/33307#issuecomment-1191662836
