### ISSUE TITLE
One word translation madly increase bundle size

### ISSUE THREAD

**Issue by zorn-v** [nextcloud/nextcloud-dialogs#696]
If you include `@nextcloud/dialogs` in you project, compiled js size is increased by ~120kb. 
This is insane.
Only `env.TRANSLATION` is about 42kb for one word. Also some size is added for `getText` dances.
I do not need it at all in my project, I even does not use `showUndo` function.

Check complied js in dist please.

**Comment by ChristophWurst** [comment]
Right now translations are injected via an env var. I'm assuming that could be a reason why the bundles are not tree-shakeable.

**Comment by zorn-v** [comment]
Also it injected as is with autors info etc and parsed with gettext in runtime. It is also no good.

**Comment by zorn-v** [comment]
Undeprecate `OC.Notification` please, I write convenient thin wrapper myself.
Without unnecessary `babel` in every `@nextcloud/*` package and `gettext` which is not tree-shakable at all. 
I do not want bloat my js bundles "just because it better".
Apps should run in NC, not as standalone. Why I need to include all that dead code in js file which users should download ?

**Comment by ChristophWurst** [comment]
Then please stay on OC.Notification. If you object the deprecation please send a PR against the server repo for discussion.

**Comment by zorn-v** [comment]
Just for information - if remove `babel` and translation related things from `rollup.config.js`, builded `index.es.js` is about 20-30kb size.

> Then please stay on OC.Notification

Deprecation mean "sometime it will be removed". So...

> If you object the deprecation please send a PR against the server repo for discussion.

I honestly try to resolve "bloat problem" with this package, but problem is much deeper. Babel polyfils/node-gettext which is not tree-shakable. Yes they do not run when not needed (and babel not needed at all as type script already compile to es5) but JS SIZE. Check builded js files please. There is IE8 checks presents which includes EVERYWHERE...
It is not only this repo problem. 
Do you check latest `password-confirm` ? 
When I try to update from `1.0.1` to latest version, my bundle increased from 250kb (which is also big coz `dialogs`) to >2MB...
WAT ? 
Reverted to 1.0.1 of cause after that :smile:
