### ISSUE TITLE
Double X (close button) on success or error messages in dashboard stable25

### ISSUE THREAD

**Issue by SwikritiT** [nextcloud/nextcloud-dialogs#725]
We are using the `"@nextcloud/dialogs": "^3.1.2" `   in the dashboard for the https://github.com/nextcloud/integration_openproject app to show the toast when the notification is marked as read.

The problem is that in the toast the `close` button is displayed twice

![Screenshot from 2022-12-15 15-57-35](https://user-images.githubusercontent.com/41103328/207832606-537f832c-6d16-4c02-acfb-f0ff3889aceb.png)

Weirdly, this problem only exists in the dashboard. On other pages, the close sign is displayed only once.

I'm importing the dialogs like this
```js
import { showError, showSuccess } from '@nextcloud/dialogs'
import '@nextcloud/dialogs/styles/toast.scss'
```
If I remove the import of scss file the double cross mark is gone but the alignment looks bad

![Screenshot from 2022-12-15 16-03-23](https://user-images.githubusercontent.com/41103328/207834005-69613a7d-169c-4ed5-b3a8-d6dd9d42f05a.png)

If I update to the new version of dialogs then this issue is solved but the latest version is not supported by the old nextcloud versions starting from 24 to below. Also, this exists in stable 25 only and works fine with the current master and older versions.

**Comment by susnux** [comment]
For dialogs < 4 you should not need to import the styles as they are already included when using the JS.
For dialogs starting with version 4 you should not import the scss but `import '@nextcloud/dialogs/dist/index.css'`.

I can not see any changes which should affect the Nextcloud compatibility of `@nextcloud/dialogs` between 3.2.0 and 4.0.1. So you should be safe with 4.0.1 for Nextcloud 23 up to Nextcloud 27.
