### ISSUE TITLE
Add toast 

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/nextcloud-dialogs#80]
Either we add a wrapper for `OCP.Toast` or maybe we can even add the toast logic and toastify-js directly to this package.

https://github.com/nextcloud/server/blob/master/core/src/OCP/toast.js

**Comment by ChristophWurst** [comment]
Yes please!

I'd say we should try to package it. Then it's isolated and this package is less dependent on the server's global variables.

**Comment by juliushaertl** [comment]
Done with https://github.com/nextcloud/nextcloud-dialogs/pull/84

**Comment by ChristophWurst** [comment]
And shipped with https://github.com/nextcloud/nextcloud-dialogs/releases/tag/v1.1.0 :shipit:

**Comment by skjnldsv** [comment]
Question, we're not using the css in this repo, right?

**Comment by skjnldsv** [comment]
Ah right, `@nextcloud/dialogs/styles/toast`.
Hum, it means we're style relying on server for icons and stuff as we don't compile them :thinking:

**Comment by ChristophWurst** [comment]
> Ah right, `@nextcloud/dialogs/styles/toast`

But users of this lib have to import this manually, right? We should document this.

**Comment by juliushaertl** [comment]
It is documented:

> Make sure that the `@nextcloud/dialogs/styles/toast` file is included in your app to make sure that the toasts have a proper styling applied.

Now the only issue I see are the icons that are used, but we could actually just inline them in the css.

**Comment by ChristophWurst** [comment]
> It is documented

Sorry :see_no_evil:

**Comment by skjnldsv** [comment]
> Now the only issue I see are the icons that are used, but we could actually just inline them in the css.

Yep, I'm on it :)
