### ISSUE TITLE
dependency versions

### ISSUE THREAD

**Issue by korelstar** [nextcloud/nextcloud-dialogs#89]
In contrast to most (as far as I can see) other public libraries published on npmjs, `@nextcloud/dialogs` and some other `@nextcloud/*` libraries don't use always caret ranges (e.g. `^3.1.4`) for dependencies in `package.json` but use (at least partly) exact version definitions (e.g. `3.1.4`). As a result, apps that are using some `@nextcloud/*` libraries, must install many different version of the same library, even if they are compatible and differ only in their patch state. As a result, the notes app, e.g., includes three different versions of `core-js` (3.5.0, 3.6.1 and 3.6.4, see https://github.com/nextcloud/notes/blob/7f689e5abee9e618748e98c9c1d8073af21731bf/package-lock.json).

This looks not very elegant and I'm wondering if this is really intended. Shouldn't we switch to care ranges?

Another issue in this context is the release management of `@nextcloud/*` libraries: with behalf of dependabot, the master branch is kept up-to-date. However, sometimes, releases with those new dependencies take a long time until they are published. This increases the impact of the first issue (exact versions). But even with the proposed fix for the first issue, a better release management could be helpful (e.g. new releases at least once a month; releases for libraries are done with respect to the dependency graph from the leaves to the root(s) with updating all dependencies before release; maybe this could be done with behalf on GitHub Actions?).

@ChristophWurst @skjnldsv @juliushaertl 

referring https://github.com/nextcloud/server/issues/15932

**Comment by skjnldsv** [comment]
Would you recommend something like core-js^3 ?

**Comment by korelstar** [comment]
I'm not a pro on this. But I see that most other libraries use this style: `"core-js": "^3.6.4"`. The advantage is that a current version is enforced but it is open for even newer versions (within the same major version). But `"core-js": "^3"` should be fine, too, under the assumption that apps do not update only the first level dependencies.

**Comment by ChristophWurst** [comment]
Yep, you may blame me. I think I changed a few version to pin them in the initial implementation. Now that we use proper semver in most places we should totally widen the version ranges!

> However, sometimes, releases with those new dependencies take a long time until they are published

This is a non-technical issue. Right now @skjnldsv releases the `@nextcloud/vue` and I do the rest, while everyone in the npm org should have permissions to do a release. You can ping me anytime to update a package.

I don't think an updated release workflow could work as it's hard to tell if a patch to the library code or a dependency update is a breaking or non-breaking change for the consumers of the package.

**Comment by korelstar** [comment]
Okay. So it's fine if I change the dependencies to caret ranges? Then I would provide a PR whenever I see a Nextcloud package that doesn't use this.

**Comment by ChristophWurst** [comment]
I updated a few `package.json`'s today as I updated packages for the security bumps
